baseURL: "https://www.janmazza.com" 
title: Jan Mazza
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: CV
          url: resume.pdf
          weight: 4
        - name: Media
          url: media/
          weight: 5 

params:
    description: "PhD candidate in Economics at the EUI and Research Fellow at Bologna University. Currently visiting Pompeu Fabra"
    author: Jan Mazza
    googleAnalyticsID: "336480863"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research", "teaching", "cv", "media"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jan Mazza
          subtitle: |
            I am a PhD candidate in Economics at the European University Institute and a Research Fellow at the University of Bologna. 
            At the moment, I am visiting Pompeu Fabra University.
            <br><br>
            My research interests include, among others, inter-generational inequality, household finance, international macro, and health.
            <br><br>
            Here, you can find my <a href=resume.pdf>CV</a>, my [Google Scholar](https://scholar.google.com/citations?user=sbrAYfUAAAAJ&hl=it), and my [Github](https://github.com/janmazza) profiles. You can also find me on [Twitter/X](http://twitter.com/jan_mazza) - mostly ranting about Italian politics and Juventus FC.
            <br><br>
            You can contact me at jan[dot]mazza[at]eui[dot]eu.
          imageUrl: "icon.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jan Mazza
          buttons:
            # - name: Papers 
            #   url: papers/
            - name: Research
              url: research/
            - name: Teaching
              url: teaching/
            - name: CV
              url: resume.pdf
            - name: Media
              url: media/
            # - name: Tags
            #   url: tags/

    socialIcons:
        - name: CV
          url: resume.pdf
        - name: Email
          url: mailto:jan.mazza@eui.eu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=sbrAYfUAAAAJ&hl=it
        - name: GitHub
          url: https://github.com/janmazza
        - name: Twitter
          url: https://twitter.com/jan_mazza

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jan Mazza"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2